### ISSUE TITLE
Dosent work on quilt

### ISSUE THREAD

**Issue by CuteistCat** [booky10/StackDeobfuscator#9] opened 2024-01-19 14:06 UTC
**Describe the bug**
When the setting to remap all log mesages is enabled it dosent remap them
**To Reproduce**
1. Enable remapping of all log messages
2. Put class_310 in chat to log it
3. Read logs
4. Find that it says class_310 not wutever the yarn maping is

**Expected behavior**
it to remap classes in log

**Screenshots**

**Minecraft Version:** 1.20.1
**Fabric Loader Version:** N/A
**Mod version:** 1.4.2

**Additional info**
Probly becuase QuiltMC/quilt-loader#229

**Comment by CuteistCat** [comment] 2024-01-19 14:09
At least notenothcrashes remaps crash reports

**Comment by booky10** [comment] 2024-01-19 14:12
This is an issue caused by quilts loader, quilt is currently unsupported. Crash reports should still be remapped.
See https://github.com/QuiltMC/quilt-loader/issues/229

**Comment by CuteistCat** [comment] 2024-01-19 14:15
didnt i say that at the buttom of my report

**Comment by CuteistCat** [comment] 2024-01-19 14:16
i recommend adding quilt to breaks in mod.json as for crashes u can use not enoth crashes expet on snapshots

**Comment by CuteistCat** [comment] 2024-01-19 14:16
or u can just put "QUILT NoT SUPPORTED" in a header at the top of the modrinth page

**Comment by booky10** [comment] 2024-01-19 16:56
> didnt i say that at the buttom of my report

You mentioned the quilt loader issue (which I missed, oops). You just mentioned "At least notenothcrashes remaps crash reports", which sounds like this mod doesn't remap crash reports.

> i recommend adding quilt to breaks in mod.json as for crashes u can use not enoth crashes expet on snapshots

This mod doesn't break with quilt. Remapping crash reports works fine.

> or u can just put "QUILT NoT SUPPORTED" in a header at the top of the modrinth page

If this mod was supported on Quilt, it wouldn't say "Fabric", it would say "Fabric, Quilt". You are on your own with Quilt.

---

The incompatibility with Quilt is already tracked by #5, so I'm closing this issue.

**Closed by booky10** 2024-01-19 16:56 UTC
Labels: bug

**Comment by CuteistCat** [comment] 2024-01-19 18:07
when this was  made #5 was nammed in such a way that it suggested only being for quilt mappings
